### ISSUE TITLE
No unifying `Event` sum type

### ISSUE THREAD

**Issue by TomMD** [onrock-eng/github-webhooks#3]
Applications using webhooks should only need one endpoint.  Servant applications need each route to have a single type for the ReqBody.  Combining these two, it seems reasonable to have a sum type to allow a single servant route to receive any event without resorting to an Aeson Object or something similarly generic.

I propose we add a sum type:

```
data Event = EvPush PushEvent
                    | EvIssue IssuesEvent
                    | ...
instance FromJSON Event ...
```

Would a patch to this effect be accepted?

**Comment by donkeybonks** [comment]
Yes, this is a good idea. I avoided implementing it initially because it is somewhat covered by other packages.

**Comment by donkeybonks** [comment]
@TomMD will you be working on this?

**Comment by TomMD** [comment]
@donkeybonks  Sorry no. It was my original intent but time got (and remains) tight.  I typed up a big sum type but without more, such as JSON instances, it isn't useful.  Also the sum type void of any type tags doesn't fill my needs of working well with servant-github-webhook.

**Comment by donkeybonks** [comment]
This one is actually tricky because there is no FromJSON object that could ever work. The sum type is encoded in the body header.

There is an example of handling multiple at the same endpoint under examples/ . There is some support in ‘github-servant-webhooks’. @TomMD

**Comment by donkeybonks** [comment]
I'm going to close this for now because it has dead-ended and it isn't really needed due to the extensive support by  `github-servant-webhooks`. If somebody comes up with a good way of doing this and wants it for `scotty` or whatever, they can feel free to open another issue.
