### ISSUE TITLE
withText label for decoding HookCheck* is non-specific

### ISSUE THREAD

**Issue by donkeybonks** [onrock-eng/github-webhooks#34]
It looks like there was a mistake made here - these labels should be made more specific.

For example, they all read `Hook check suite status`.

**Comment by AlistairB** [comment]
Hi, I'm not sure if I follow. What is an example of a label that should be more specific? Perhaps can you link a line number in the src?

**Comment by donkeybonks** [comment]
Not sure how to select independent lines, but at the top and bottom of this range for example
https://github.com/onrock-eng/github-webhooks/blob/3ce859f01351e328d87cbf9c28e85de0269795ba/src/GitHub/Data/Webhooks/Events.hs#L151,L192

**Comment by AlistairB** [comment]
Ah oops thanks. I'll make a PR in a few hours.
