### ISSUE TITLE
Who is using github-webhooks? Add some logos in README

### ISSUE THREAD

**Issue by kvanbere** [onrock-eng/github-webhooks#71]
I would like to add a section to the README showcasing some of the projects that use this dependency. If anyone is interested in telling their story, we would love to hear it.

@AlistairB 
@rob-b 
@roberth 
@matthewbauer 
@sorki 
@domenkozar 
@TomMD 
@artemohanjanyan 
@sir4ur0n

**Comment by kvanbere** [comment]
@halletj
@sorki 
@rahulmutt 
@ghuntley - by the way you profile says Kangaroo Island, nice! My family is from there. We might be related?
@Exegetech

**Comment by roberth** [comment]
[Hercules CI](https://hercules-ci.com) was built with it from the start. It's CI/CD tooling for Nix based projects, offering a scheduler as a service.

@kvanbere - by the way you have a Dutch family name. Know any Hensings in Australia?

**Comment by kvanbere** [comment]
@roberth thanks, I do not sorry, my family immigrated to Australia a long time ago running away from WW2 in Holland. I have ran into a few 'van der' but not any Hensing yet.

Can you grant us permission to use the logo somewhere in the readme?

**Comment by roberth** [comment]
> family

Similar time frame I think. Not many of them and I don't really know them. Thought Australia was like a village ;)

> permission

Of course! That's something I can do, so here you go. You are allowed to use the logo, until further notice, in the github-webhooks README to promote the github-webhooks project with accompanying text as below or as agreed.

How about something like this? You can get the markdown with the edit button.
"From the start" could be misinterpreted, so I removed that.

<table><tbody>
<tr>
<td align=right>

[<img src="https://github.com/cuedo/github-webhooks/assets/496447/c80a498f-2e68-45b8-bf20-a5f2f15eda56" height="96"/>](https://hercules-ci.com)

</td>
<td>

[Hercules CI](https://hercules-ci.com) was built with `github-webhooks`. It provides CI/CD tooling for [Nix](https://nixos.org/nix) based projects, offering a scheduler as a service. It accepts push events and many more, from github.com and GitHub Enterprise instances.

</td>
</tr>
</table>

**Comment by kvanbere** [comment]
That formatting and writeup is great, I'm going to use it, thanks!

**Comment by sir4ur0n** [comment]
Why was I tagged on this issue? :sweat_smile:

**Comment by kvanbere** [comment]
> Why was I tagged on this issue? 😅

I tagged everyone in Analytics > Contributors, and Analytics > Forks > All time
